# Generated by Django 3.1.5 on 2021-01-28 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBranches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SupportedBanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_api', models.CharField(max_length=100)),
                ('token_lifetime_in_minutes', models.SmallIntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='BankConnections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30)),
                ('account_name', models.CharField(max_length=70)),
                ('connected', models.BooleanField(default=False)),
                ('valid_token', models.CharField(default='', max_length=250)),
                ('established_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connection', to='bank.bankbranches')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bankbranches',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='bank.supportedbanks'),
        ),
    ]
